name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh key yaratsish
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600  ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{vars.HOST}} > ~/.ssh/known_hosts

      - name: serverga ulanish
        run: ssh ${{vars.USER}}@${{vars.HOST}}

      - name: repozitorylarni yangilash
        run: |
          ssh ${{vars.USER}}@${{vars.HOST}} << 'EOF'
          cd  projects/Tijara
          git pull origin main
          EOF
